# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Goldwash Music
email: goldwashmusic@gmail.com
description: Existential Funk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://goldwash.github.io/site" # the base hostname & protocol for your site
github_username:  goldwash

# Build settings
markdown: kramdown
